version: '3.7'

services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    environment:
      blobHost: "0.0.0.0"
      blobPort: 8888
    ports:
      - 10000:10000
      - 8888:8888
